heading: "Brink"
subheading: "Ruinen"

logo: "/public/assets/images/logo/logo-resize.png"
favicon: "/public/assets/images/logo/favicon.ico"
header: "/public/assets/images/header.jpg"

url: "https://t0mmie.github.io"
baseurl: "/brink-ruinen"

menu:
  - title: "Home"
    url: "/"
  - title: "Over ons"
    url: "/over-ons"
  - title: "Repertoire"
    url: "/repertoire"
  - title: "Foto's"
    url: "/fotos"
  - title: "Agenda"
    url: "/agenda"
  - title: "Contact"
    url: "/contact"
